### ISSUE TITLE
Not able to clone the repository

### ISSUE THREAD

**Issue by aniketbote** [dragnet-org/dragnet#78]
When I followed the instructions given in description I got a permission denied error.
Complete messege:
C:\Users\devda>git clone git@github.com:seomoz/dragnet.git
Cloning into 'dragnet'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by pakelley** [comment]
I still seem to be able to clone the repo, sounds like maybe you have an ssh key on your account that isn't being used? (i.e. maybe you just need to `ssh-add /path/to/ssh/key`?)

**Comment by trifle** [comment]
@aniketbote This definitely sounds like a git configuration error, not an issue with this repo.
If you want a quick bypass, try cloning with http (`git clone https://github.com/dragnet-org/dragnet.git`) instead of git.

**Comment by b4hand** [comment]
You can only use the `git@github.com` SSH URL if you have write permissions to the repo. You'll want to use the `https` URL instead. Also, the README.md was pointing at the older URL name. I've fixed that in #97.
