### ISSUE TITLE
publish a new release on pypi?

### ISSUE THREAD

**Issue by bdewilde** [dragnet-org/dragnet#84]
Hi! It's been about a year since the last release — and [my previous ask](https://github.com/dragnet-org/dragnet/issues/60) for it ;) — and I was wondering if folks had bandwidth to publish a new (v2.0.4?) release to pypi. It would be great to get unblocked on upgrading `scikit-learn` to v0.20. Thanks in advance!

**Comment by matt-peters** [comment]
I'm all for pushing a new release.  Who has access to create a new release other then me?  It would also be great to have someone review and merge in the two open PRs before the new release.

**Comment by bdewilde** [comment]
That's a good question... @pakelley or @b4hand , maybe?

**Comment by pakelley** [comment]
I don't have permission to merge or release a package, but I'd be happy to help review those PRs if you want @matt-peters

**Comment by bdewilde** [comment]
Would either of you _like_ to have permissions to merge PRs and publish releases? If so... @matt-peters , would you be able to grant them? I'd volunteer but I'm not confident that I have enough bandwidth to maintain another project... Maybe I can be a backup plan? :)

**Comment by pakelley** [comment]
Yeah, I'd be happy to help out with that if @matt-peters is open to it

**Comment by b4hand** [comment]
I looked at both open PRs, but I'm not sure if either is ready to merge. It's probably better to just go ahead and create a new release. I can grant permissions to the project if @matt-peters approves.

**Comment by matt-peters** [comment]
I'm all for adding additional collaborators with write access to the repo, and ability to push a new release to pypi.  My bandwidth for maintaining this is pretty low at this point, but it is still fairly actively used as far as I know.

**Comment by bdewilde** [comment]
Hi @matt-peters , just following up on this. Could you grant repo write access to @pakelley, and make him a maintainer of the package on pypi? If you'd like an additional pair of helping hands, I volunteer as tribute, and will coordinate with Patrick.

**Comment by b4hand** [comment]
I've granted @bdewilde and @pakelley write access to the repo.

**Comment by b4hand** [comment]
I can grant access to pypi, but I'll need your usernames there. I couldn't find either of you listed as @bdewilde and @pakelley.

**Comment by bdewilde** [comment]
Thanks a ton, @b4hand ! On PyPi, I'm @bjdewilde.

**Comment by b4hand** [comment]
bjdewilde has been added to pypi.

**Comment by bdewilde** [comment]
Alright! Let's see now about publishing a minor 2.0.4 release. Is there anything special that has to be done for the cython files? If not, here's a checklist:

- [ ] write up a changelog (and add a `CHANGES.md` file to the repo, maybe?)
- [ ] bump package version in [`setup.py`](https://github.com/dragnet-org/dragnet/blob/master/setup.py#L69)
- [ ] tag a [release](https://github.com/dragnet-org/dragnet/releases) on the github repo
- [ ] build source dist and wheels for PY3 (and PY2?) via `python setup.py sdist bdist_wheel`
- [ ] upload the distribution archives to pypi via `python -m twine upload`

Anything I've missed here?

**Comment by pakelley** [comment]
I didn't have my own PyPi account before, but I created one (@pakelley). I'll be away for the rest of this week, but I can help out with preparing the release next week 👍

**Comment by matt-peters** [comment]
Awesome, thanks everyone for taking this on! I can't remember the details regarding the cython files, but don't think there was anything special as they are distributed with the package and built locally on installation.

**Comment by b4hand** [comment]
Probably a good idea to put the release instructions in the README just so we don't forget later. It's always a pain to try to figure it out when you just want to make a release quickly.

**Comment by b4hand** [comment]
pakelley is added to pypi as well

**Comment by bdewilde** [comment]
Just a heads-up: I've gotten through all the steps except for publishing the release on PyPi and tagging it here on GitHub. I built a source distribution as well as PY2 + PY3 wheels, and all existing tests pass, so I'm assuming that everything is _okay_.

Apologies in advance if I've screwed something up. 🙏

**Comment by bdewilde** [comment]
PyPi: https://github.com/dragnet-org/dragnet/releases/tag/2.0.4
GitHub: https://github.com/dragnet-org/dragnet/releases/tag/2.0.4
