### ISSUE TITLE
port existing tests to `pytest`

### ISSUE THREAD

**Issue by bdewilde** [dragnet-org/dragnet#88]
Currently, `dragnet` has `unittest`-based tests run via `nose`, but we could and probably should take advantage of a more modern and maintained testing framework like [`pytest`](https://docs.pytest.org). This is more of a chore than an issue, but just wanted to assess buy-in before writing any code.

Tasks:
- port the tests into `pytest`-style
- update testing dependencies in `requirements.txt`
- bonus: get Travis CI running tests via `pytest` (side note: is the `make test` command in `.travis.yml` actually working??)

**Comment by b4hand** [comment]
I'm in favor. The Travis build was working at one point in time, but I don't know if it's been checked since the project was moved

**Comment by bdewilde** [comment]
Going to close this since PR #89 was merged, but would be great to (separately) figure out why Travis CI doesn't seem to be running.
